### ISSUE TITLE
Display results in scientific notation

### ISSUE THREAD

**Issue by matilde-t** [JordanL2/ModularCalculator#43]
I can do the calculations using the E notation, but it would be very useful to have the results displayed in the same style

**Comment by JordanL2** [comment]
Raised issue to add this option to the interface for next release:
https://github.com/JordanL2/ModularCalculatorInterface/issues/25

**Comment by JordanL2** [comment]
Done, will appear in interface version 1.4.0.

**Comment by JordanL2** [comment]
@matilde-t in the mean time, you can convert a number into scientific E notation with the `scientific` function, eg:

```scientific(1000)```

outputs

```1E3```
