### ISSUE TITLE
Trigonometry functions return value is not recognized as a number

### ISSUE THREAD

**Issue by Tommimon** [JordanL2/ModularCalculator#58]
When I try to combine a trigonometry function with normal number operators I get an error, example:
```
a = tan(2)+2
```
produces:
```
Could not execute operator + with operands: '-2.185039863261519', 'Number(2)' - Operator + parameter 1 must be of type(s) number
```
screenshot:
![image](https://github.com/user-attachments/assets/94b3d862-e800-4ecf-b229-72396a1fcfb9)

By contrast, other functions such as logarithmic functions work as intended:
```
a = log(2)+2
```
produces
```
2.693147180559945309417232121458
```

In python it is possible to combine `tan` with other operators so I don't understand the problem, for reference in python:
```
import math
print(math.tan(2)+2)
```
output:
```
-0.1850398632615189
```

Can you reproduce the same problem or is it related to my setup? I'm trying to package the application for nix so that could be the problem, but I don't understand why other functions work.

**Comment by JordanL2** [comment]
I see the problem and will fix it asap.

**Comment by JordanL2** [comment]
@Tommimon latest release 1.5.2 has the fix for this issue.
