### ISSUE TITLE
Fractional numbers and zero give wrong results as logarithm bases

### ISSUE THREAD

**Issue by Tommimon** [JordanL2/ModularCalculator#59]
I can't find the relative code but I think logarithm bases are floored before `log` function is applied, this gives wrong results, here is an example input if you want to try:

```
log(100,10)
log(10,10)
log(1,10)
log(0.1,10)
log(0.01, 10)

log(100,10.7)
log(10,10.6)
log(1,10.5)
log(0.1,10.4)
log(0.01, 10.1)

log(100, 0)
log(10, 0)
log(1, 0)
log(0.1, 0)
log(0.01, 0)

log(100, 0.1)
log(10, 0.1)
log(1, 0.1)
log(0.1, 0.1)
log(0.01, 0.1)

log(2.56, 1.6)
log(1.6, 1.6)
log(1, 1.6)
log(0.625, 1.6)
log(0.390625, 1.6)
```

The problem is that for number with a fractional part only integer part is considered, so `10.7` gives same result as `10`:

![image](https://github.com/user-attachments/assets/4b00df19-753b-474c-b430-4a614273126e)

Base `1.6` gives an error because is considered as base `1` which is meant to trigger an error.
Base `0.1` gives same results as base `0`, but this result shouldn't be zero, it should instead trigger a domain error as for negative numbers.

Python output for reference correct results:
![image](https://github.com/user-attachments/assets/fa39882e-29e6-4f98-b4a8-819aff08b759)

**Comment by JordanL2** [comment]
I see the problem, bases are being converted into ints, will fix.

**Comment by JordanL2** [comment]
Will be fixed in the next version, will release it soon.

**Comment by Tommimon** [comment]
I don't know if the problem related to base `0` is related to integer conversion. might be a different issue.

**Comment by JordanL2** [comment]
Different issue, but also fixed.

**Comment by JordanL2** [comment]
@Tommimon ModularCalculatorInterface 1.5.3 (including ModularCalculator 1.4.3) has been released, which includes this fix :) (Flatpak is being updated now.)
